export var allData = [{
    "image": "assets/image/a.jpg",
    "name": "vid first",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/b.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/g.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidyesh second",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidyesh",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidyesh",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidyesh",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidyesh",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidy",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidy",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidy",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidy",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vidy",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid2222",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid2222",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid2221",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vinay",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vinay",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "john",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "rock",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
},
{
    "image": "assets/image/a.jpg",
    "name": "vid last",
    "profession": "S/W Devloper",
    "MemberID": "116161",
    "age": "29",
    "religion": "Hindu",
    "MotherTounge": "Marathi",
    "height": "5.8",
    "caste": "Bramhin",
    "MaritalStatus": "Married",
    "location": "pune"
}]
 